[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
kafka = "0.10"
apache-avro = "0.17.0"
anyhow = "1.0"
# serde_avro_derive = "0.3.1"
serde_avro_fast = "2.0.0"
serde_derive = "1.0.215"
serde = "1.0.215"
